# Dynmap-Factions configuration
#
update:
  # Seconds between checks for Factions updates
  period: 300

layer:
  name: "Factions"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 2

# Format for popup - substitute values for macros
infowindow: '<div class="infowindow"><span style="font-size:120%;">%regionname%</span><br />Flags<br /><span style="font-weight:bold;">%flags%</span></div>'

regionstyle:
  strokeColor: "#FF0000"
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: "#FF0000"
  fillOpacity: 0.35
  homeicon: "redflag"
  
# Optional setting to limit which regions to show, by name - if commented out, all regions are shown
visibleregions:
#  - faction1
#  - faction2
  
# Optional setting to hide specific regions, by name
hiddenregions:
#  - hiddenfaction
#  - secretsite
  
# Optional per-region overrides for regionstyle (any defined replace those in regionstyle)
custstyle:
  SafeZone:
    strokeColor: "#0000FF"
    fillColor: "#0000FF"
  WarZone:
    strokeColor: "#404040"
    fillColor: "#404040"
